// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransferMoney.Data.Context;

namespace TransferMoney.Data.Migrations
{
    [DbContext(typeof(TransferMoneyDbContext))]
    [Migration("20210606130705_TransferMoneyMigration")]
    partial class TransferMoneyMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TransferMoney.Domain.Entities.TransferEntity", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AccountDestination")
                        .HasColumnType("longtext");

                    b.Property<string>("AccountOrigin")
                        .HasColumnType("longtext");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<double>("Value")
                        .HasColumnType("double");

                    b.HasKey("TransactionId");

                    b.ToTable("Transfers");
                });
#pragma warning restore 612, 618
        }
    }
}
